version: '3.1'

services:

  db:
    image: mysql:8.0.36-bullseye
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: star-wars
      MYSQL_USER: development
      MYSQL_PASSWORD: development
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
    - 3306:3306
